# Generated by Django 3.1.7 on 2021-03-15 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0003_auto_20210225_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=256)),
                ('type', models.TextField(choices=[('company', 'company'), ('individual', 'individual')])),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.TextField(max_length=256)),
                ('address_line', models.TextField(max_length=256)),
                ('city', models.TextField(max_length=256)),
                ('state', models.TextField(max_length=256)),
                ('zip_code', models.TextField(max_length=256)),
                ('country', models.TextField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('delivery_date', models.DateTimeField()),
                ('quantity', models.PositiveIntegerField(max_length=10)),
                ('sale_total', models.FloatField()),
                ('status', models.TextField(choices=[('PENDING', 'PENDING'), ('SHIPPED', 'SHIPPED'), ('RECEIVED', 'RECEIVED')])),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouse')),
            ],
        ),
    ]
