# Generated by Django 3.1.7 on 2021-03-18 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20210318_0139'),
        ('sales', '0002_salespart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.part'),
        ),
    ]
