# Generated by Django 3.1.7 on 2021-03-18 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_type', models.TextField(choices=[('ORDER', 'ORDER'), ('MANUFACTURE', 'MANUFACTURE'), ('SALE', 'SALE')], default='ORDER')),
                ('t_date', models.DateTimeField(auto_now_add=True)),
                ('t_balance', models.DecimalField(decimal_places=2, max_digits=9)),
                ('t_item_name', models.CharField(max_length=100)),
                ('t_serial', models.BigIntegerField(default=500000)),
                ('t_quantity', models.IntegerField(default=0)),
            ],
        ),
    ]
