# Generated by Django 3.1.7 on 2021-02-24 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=80, unique=True)),
                ('p_unit_value', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('p_size', models.IntegerField(blank=True, default=1, null=True)),
                ('p_color', models.CharField(blank=True, max_length=7, null=True, unique=True)),
                ('p_finish', models.TextField(blank=True, choices=[('Matte', 'Matte'), ('Glossy', 'Glossy'), ('Chrome', 'Chrome')], default='Glossy', null=True)),
                ('p_grade', models.TextField(blank=True, choices=[('Aluminum', 'Aluminum'), ('Steel', 'Steel'), ('Carbon', 'Carbon')], default='Aluminum', null=True)),
                ('p_type', models.TextField(blank=True, choices=[('Raw Material', 'Raw Material'), ('Part', 'Part')], default='Part', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_name', models.CharField(max_length=80, unique=True)),
                ('v_price_multiplier', models.DecimalField(decimal_places=5, max_digits=9)),
                ('v_address', models.CharField(max_length=120)),
                ('v_city', models.CharField(max_length=120)),
                ('v_province', models.CharField(max_length=120)),
                ('v_postal_code', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w_name', models.CharField(max_length=80, unique=True)),
                ('w_address', models.CharField(max_length=120)),
                ('w_city', models.CharField(max_length=120)),
                ('w_province', models.CharField(max_length=120)),
                ('w_postal_code', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='SellsParts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_quantity', models.IntegerField(default=1)),
                ('p_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.part')),
                ('v_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('prod_type', models.TextField(choices=[('Mountain Bike', 'Mountain Bike'), ('Road Bike', 'Road Bike'), ('Hybrid Bike', 'Hybrid Bike')], default='Hybrid Bike')),
                ('prod_weight', models.DecimalField(decimal_places=2, max_digits=9)),
                ('p_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.part')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status', models.TextField(choices=[('PENDING', 'PENDING'), ('SHIPPED', 'SHIPPED'), ('RECEIVED', 'RECEIVED')], default='PENDING')),
                ('order_quantity', models.IntegerField(default=1)),
                ('order_total_cost', models.DecimalField(decimal_places=2, max_digits=9)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('p_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.part')),
                ('v_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.vendor')),
                ('w_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='MadeOf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('part_FK_child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='madeof_child_part', to='inventory.part')),
                ('part_FK_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='madeof_parent_part', to='inventory.part')),
            ],
        ),
        migrations.CreateModel(
            name='Contains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_quantity', models.IntegerField(default=1)),
                ('p_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.part')),
                ('w_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse')),
            ],
        ),
    ]
