# Generated by Django 3.1.7 on 2021-02-24 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=80, unique=True)),
                ('p_unit_cost', models.DecimalField(decimal_places=2, max_digits=9)),
                ('p_size', models.IntegerField(default=1)),
                ('p_color', models.CharField(max_length=7, unique=True)),
                ('p_finish', models.TextField(choices=[('Matte', 'Matte'), ('Glossy', 'Glossy'), ('Chrome', 'Chrome')], default='Glossy')),
                ('p_grade', models.TextField(choices=[('Aluminum', 'Aluminum'), ('Steel', 'Steel'), ('Carbon', 'Carbon')], default='Aluminum')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_type', models.TextField(choices=[('Mountain Bike', 'Mountain Bike'), ('Road Bike', 'Road Bike'), ('Hybrid Bike', 'Hybrid Bike')], default='Hybrid Bike')),
                ('prod_weight', models.DecimalField(decimal_places=2, max_digits=9)),
                ('prod_model', models.CharField(max_length=10, unique=True)),
                ('prod_size', models.TextField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], default='Medium')),
                ('prod_color', models.CharField(max_length=7, unique=True)),
                ('prod_finish', models.TextField(choices=[('Matte', 'Matte'), ('Glossy', 'Glossy'), ('Chrome', 'Chrome')], default='Glossy')),
                ('prod_grade', models.TextField(choices=[('Aluminum', 'Aluminum'), ('Steel', 'Steel'), ('Carbon', 'Carbon')], default='Aluminum')),
            ],
        ),
        migrations.CreateModel(
            name='RawMaterials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rm_name', models.CharField(max_length=80, unique=True)),
                ('rm_unit_cost', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.CharField(max_length=80)),
                ('field2', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_name', models.CharField(max_length=80, unique=True)),
                ('v_price_multiplier', models.DecimalField(decimal_places=5, max_digits=9)),
                ('v_address', models.CharField(max_length=120)),
                ('v_city', models.CharField(max_length=120)),
                ('v_province', models.CharField(max_length=120)),
                ('v_postal_code', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w_name', models.CharField(max_length=80, unique=True)),
                ('w_address', models.CharField(max_length=120)),
                ('w_city', models.CharField(max_length=120)),
                ('w_province', models.CharField(max_length=120)),
                ('w_postal_code', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='SellsRM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rm_quantity', models.IntegerField(default=1)),
                ('rm_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.rawmaterials')),
                ('v_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='SellsParts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_quantity', models.IntegerField(default=1)),
                ('part_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.parts')),
                ('v_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='OrderRM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status', models.TextField(choices=[('PENDING', 'PENDING'), ('SHIPPED', 'SHIPPED'), ('RECEIVED', 'RECEIVED')], default='PENDING')),
                ('order_quantity', models.IntegerField(default=1)),
                ('rm_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.rawmaterials')),
                ('v_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.vendor')),
                ('w_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='OrderParts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status', models.TextField(choices=[('PENDING', 'PENDING'), ('SHIPPED', 'SHIPPED'), ('RECEIVED', 'RECEIVED')], default='PENDING')),
                ('order_quantity', models.IntegerField(default=1)),
                ('part_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.parts')),
                ('v_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.vendor')),
                ('w_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='MadeOfSubParts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_quantity', models.IntegerField(default=1)),
                ('part_1_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='madeofsubparts_parent_product', to='inventory.parts')),
                ('part_2_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='madeofsubparts_child_part', to='inventory.parts')),
            ],
        ),
        migrations.CreateModel(
            name='MadeOfRM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rm_quantity', models.IntegerField(default=1)),
                ('part_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.parts')),
                ('rm_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.rawmaterials')),
            ],
        ),
        migrations.CreateModel(
            name='MadeOfParts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_quantity', models.IntegerField(default=1)),
                ('part_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.parts')),
                ('product_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.products')),
            ],
        ),
        migrations.CreateModel(
            name='ContainsRM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rm_quantity', models.IntegerField(default=1)),
                ('rm_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.rawmaterials')),
                ('w_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='ContainsProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_quantity', models.IntegerField(default=1)),
                ('product_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.products')),
                ('w_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='ContainsParts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_quantity', models.IntegerField(default=1)),
                ('part_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.parts')),
                ('w_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse')),
            ],
        ),
    ]
