# Generated by Django 3.1.7 on 2021-02-25 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20210225_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='p_type',
            field=models.TextField(choices=[('Raw Material', 'Raw Material'), ('Part', 'Part'), ('Product', 'Product')], default='Part'),
        ),
    ]
