# Generated by Django 3.1.7 on 2021-02-24 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20210224_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderparts',
            name='order_total_cost',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderrm',
            name='order_total_cost',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=9),
            preserve_default=False,
        ),
    ]
