# Generated by Django 3.1.5 on 2021-02-01 23:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailnotification',
            name='users',
            field=models.ManyToManyField(related_name='notification', through='utils.EmailNotificationUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
