# Generated by Django 3.1.5 on 2021-02-02 01:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('utils', '0002_auto_20210201_2351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailnotification',
            old_name='text',
            new_name='message',
        ),
        migrations.AddField(
            model_name='emailnotification',
            name='subject',
            field=models.CharField(default='subject', max_length=100),
        ),
        migrations.AlterField(
            model_name='emailnotification',
            name='users',
            field=models.ManyToManyField(related_name='notifications', through='utils.EmailNotificationUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
