# Generated by Django 3.1.5 on 2021-02-02 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0003_auto_20210202_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailnotification',
            name='subject',
            field=models.CharField(max_length=100),
        ),
    ]
