# Generated by Django 3.1.7 on 2021-03-27 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auto_20210325_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='notify_by_email',
            field=models.BooleanField(default=False),
        ),
    ]
