# Generated by Django 3.1.7 on 2021-04-07 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_subscription_notify_by_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-timestamp']},
        ),
    ]
